#!/bin/bash

##############################################################################
## © Copyright IBM Corp. and Jean-Yves Girard (jeanyvesgirard@free.fr) 2022-2024
##
## OSO Terminal v1.0.5.17
## 
###############################################################################

export EP11_IBM_TARGET_HSM="4.16 3.16"

BG_BLUE="$(tput setab 4)"
BG_BLACK="$(tput setab 0)"
FG_GREEN="$(tput setaf 2)"
FG_WHITE="$(tput setaf 7)"
FG_CYAN="$(tput setaf 6)"
TOP=10



function title {
   echo -n ${BG_BLACK}${FG_CYAN}
   clear
cat <<- _EOF_
   EKMF seed import commands to OSO		           OSO Action
   -----------------------------------------               ----------------------------------------------
_EOF_
   echo -n ${BG_BLACK}${FG_WHITE}
cat <<- _EOF_
   1. Request OSO RSA Key Pair                             4. OSO PreConfirmation Queue
                                                           i. OSO PreConfirmation msg ids
   n. Create a new transport key                          
   g. Generate new seeds                                   5. OSO PostConfirmation Queue

   2. Upload a transport key  		                   6. Key Import Result
   3. Upload in OSO wrapped EKMF seeds                     r. Start OSO iteration                                   
   0. Quit

_EOF_

   tput cup $TOP 0
   echo -n ${BG_BLACK}${FG_GREEN}
   tput ed
   tput cup $(( TOP + 1 )) 0
}



tput smcup
title
while [[ $REPLY != 0 ]]; do
   tput cup $(( TOP + 1 )) 0
   echo -n ${BG_BLACK}${FG_GREEN}
   read -n 1 -t 3 -p "Enter selection > " selection
if [[ $selection != "" ]] 
then
   tput cup $TOP 0
   tput ed
   tput cup $(( TOP + 2 )) 0
   
   echo -n ${BG_BLACK}${FG_WHITE}
   echo
   NEXT=1 
   case $selection in

	1) 
		./EKMF_GetRSAPKey.sh
	;;
	4) 
		echo "PreConfirmation Queue"
		./OSOQueue.py pre | jq -rC
	;;
	i) 
		echo "PreConfirmation Queue Msg Ids"
		./OSOQueue.py pre | jq -r .documents[].id | xargs
	;;
	2) 
		R=$(./OSOQueue.py post | jq -r '.documents[0] | select((.metadata | fromjson).type == "EKMFRSAIMPORT") | (.metadata | fromjson).keyid')
		# If R is empty → read it from RSAID
		if [ -z "$R" ]; then
		    if [ -f RSAID ]; then
		        R=$(tr -d '\n' < RSAID)
		    else
		        echo "Error: no RSA id returned and RSAID file not found."
		        exit 1
		    fi
		else
		    # If R exists → store it
		    printf "%s" "$R" > RSAID
		    ./OSOQueue.py post | jq -r '.documents[0] | select((.metadata | fromjson).type=="EKMFRSAIMPORT") | .content' > public.pem 
		fi
		echo "rsa import key: $R"
#		./EKMF_SendTKEY.sh public.pem $R 8c123e3317f57abe25007fda598acba69dfa0bc8d31816e81f1426597fc99f1d
		./EKMF_SendTKEY.sh public.pem $R $(cat TKEY)
	;;
	g)      
		read -p "How many keys per thread? " KEYGENNB
		echo "Generating new seeds"
		echo 
		LIST="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16"
		for i in $LIST; do echo "Job $i started" && ./ekmfexport $(cat TKEY) "${KEYGENNB:=1}" | grep -v domain | gzip -c | base64 -w0 > K/keys_set.$i.gz.b64 & done	
		wait
		echo "All jobs finished ✅"
	;;
	n)
		echo "Generating new transport key"
		echo
		R=$(./createTKEY | grep -v Initializing)
		TKEY=$(echo "$R" | grep Generated | sed -e '1s/.* //')
		echo $TKEY > TKEY
		echo "$R" 
	;;
	5) 
		echo "PostConfirmation Queue"
		./OSOQueue.py post | jq -rC
	;;
	3) 
#		LIST="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17"
		LIST="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 "
		#LIST="1"
		for i in $LIST; do echo "Upload $i started" && bash ./EKMF_SendKeys.sh $i ; done
		wait
		echo "All uploads finished ✅"
	;;
	6) 
		./OSOQueue.py post | jq -r '.documents[] | select((.metadata | fromjson).type=="EKMFIMPORTRESULT") | .content'
	;;
	K)
		base64 -d K/keys_set.11.gz.b64 | gunzip -c | head -n 35
	;;
	r)
		echo "OSO Iteration started"
   		./OSO_StartIteration.sh
		echo "Completed"
	;;
	C)
		./EKMF_List.sh EKMFLIST
	;;
	z)
		./EKMF_List.sh EKMFROTATE
	;;
	Z)
		./EKMF_List.sh EKMFACTIVATEROTATION
	;;
	0) 
		echo "Exiting OSO Terminal"
		break
	;;
   esac
   fi
done
tput rmcup

