#!/bin/bash

#!/bin/bash

if [[ ! -f K/senderpublic.pem ]]
then
	echo "Creating sender private key"
	openssl genpkey -algorithm Ed25519 -out K/senderprivate.key
	openssl pkey -in K/senderprivate.key -pubout -out K/senderpublic.pem
fi

clear
echo "--- Select a Service to start ---"
echo "1) ekmfoso addon frontend"
echo "2) ekmfoso addon backend"
echo "3) oso frontend plugin"
echo "s) sqlite"
echo "c) crypto monitoring"
echo "q) Quit"
echo "-------------------------------------"

# -n 1 reads exactly one character and continues immediately
read -n 1 -p "Choice: " choice
echo "" # Just to move to a new line after the keypress

case $choice in
    1)
	export ED25519_PUBLIC_KEY=$(openssl pkey -pubin -in K/senderpublic.pem -pubout -outform DER | base64 -w0)
	export OSONAME=oso1
	export CLIENTCERT=$(base64 -w0 certs/client.crt)
	export CLIENTKEY=$(base64 -w0 certs/client.key)
	export CACERT=$(base64 -w0 certs/ca.crt)
       # ED25519_PUBLIC_KEY=$(base64 -w0 K/senderpublic.pem) 
	mode=frontend ./ekmfimportserver ;;
    2)
        EP11_IBM_TARGET_HSM="4.16 3.16" mode=backend ./ekmfimportserver ;;
    3)
        python FrontendPlugin.py ;;
    s)
        sqlite3 keys.db ;;
    c)
        watch -n 2 'zcryptstats -i 1 -c 1 -T -a | egrep "COUNTER|Total"' ;;
    q)
        exit 0 ;;
    *)
        echo "Invalid key." ;;
esac
