#!/bin/bash

#!/bin/bash

clear
echo "--- Select a Service to start ---"
echo "1) ekmfoso addon frontend"
echo "2) ekmfoso addon backend"
echo "3) oso frontend plugin"
echo "s) sqlite"
echo "c) crypto monitoring"
echo "q) Quit"
echo "-------------------------------------"

# -n 1 reads exactly one character and continues immediately
read -n 1 -p "Choice: " choice
echo "" # Just to move to a new line after the keypress

case $choice in
    1)
        mode=frontend ./ekmfimportserver ;;
    2)
        EP11_IBM_TARGET_HSM="4.16 3.16" mode=backend ./ekmfimportserver ;;
    3)
        python FrontendPlugin.py ;;
    s)
        sqlite3 keys.db ;;
    c)
        watch -n 2 'zcryptstats -i 1 -c 1 -T -a | egrep "COUNTER|Total"' ;;
    q)
        exit 0 ;;
    *)
        echo "Invalid key." ;;
esac
